version: '3'

services:

  virtualcashier-api:
    container_name: virtualcashier-api
    build: '.'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    networks:
      - app-connect
    ports:
      - '3333:3333'
    environment:
      - WAIT_HOSTS=postgres:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30

  postgres:
    container_name: postgres
    image: postgres:11
    restart: unless-stopped
    volumes:
      - postgres-data:/data
    environment: 
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS} 
    networks:
      - app-connect
    ports:
      - "5432:5432"

volumes:
  postgres-data:

networks:
  app-connect:
      driver: bridge
